### ISSUE TITLE
when disable default hotkey(combo and single) in ini file , all custom hotkey not work

### ISSUE THREAD

**Issue by ghost** [magicstep/ViATc-English#11]
when disable default hotkey(combo and single) in ini file , all custom hotkey not work .

ver : 0.5.5.2

**Comment by magicstep** [comment]
Thanks for notifying me,
I found that only this line is causing the problem:
EnableBuiltInHotkeys=0
The glitch is only when you disable single hotkeys. I know a way to fix it
but it takes some code and time. I think I will just remove the disabling
option for single hotkeys. I don't think anyone will use it. It is possible
to remap to <None> in the ini file.


However disabling the combo keys is good and I think this is what you asked
for. Is that true?
EnableBuiltInComboHotkeys=0

**Comment by ghost** [comment]
On my side, just set EnableBuiltInComboHotkeys=0
and still have the result that all custom combohotkey not work

**Comment by ghost** [comment]
ver : 0.5.5.3
it work !
thank a lot !
