### ISSUE TITLE
Failed to map custom commands in usercmd.ini (or is this feature not yet implemented?)

### ISSUE THREAD

**Issue by Fuann-Kinoko** [magicstep/ViATc-English#14]
First of all, thanks for your work, this script really made me pick up total commander again.

When I try to add commands from usercmd.ini for hotkeys, I keep getting mapping failed and the command is missing a `<` symbol

![](https://iili.io/L0t9Og.png)

Actually, most of the time the original commands are enough, but sometimes I want to add some fancy commands as well.

**Comment by magicstep** [comment]
Sorry for late reply.
I see you start command with em_  may I know why?
Try cm_ if em_ has no reason
On line 4688 the script is looking for cm_ and replaces it with <
`       actiontxt := Regexreplace(actiontxt,"^cm_","<") . ">"`

![2022-10-22 20_16_05-ViATc-0 5 5en ahk (c__Progs_ViATc) - GVIM](https://user-images.githubusercontent.com/28110430/197359107-b9383c2f-8a33-47fc-926d-93668956e65a.png)


I think I could modify this line so it would replace any of those two patterns like this line: 
`       actiontxt := Regexreplace(actiontxt,"^(em_|cm_)","<") . ">"`

or I could put a dot which means any letter not just c or e
`       actiontxt := Regexreplace(actiontxt,"^.m_","<") . ">"`

**Comment by magicstep** [comment]
Another question, did you change your font in Windows from Normal to Big?
I am surprised that the words don't fit in their places.
This is how it should look like:
![2022-10-22 21_04_23-Settings   VIATC 0 5 5 4](https://user-images.githubusercontent.com/28110430/197360437-7a9fc844-9bba-4421-bfe6-05c5670e7db4.png)
