### ISSUE TITLE
Reset the behavior of ";" and add normal autohotkey command

### ISSUE THREAD

**Issue by hongyuanjia** [magicstep/ViATc-English#5]
Thanks for this great plugin! It fits perfectly for my needs. Sorry, this may be a silly question. But is it possible to reset the bind command of `;`? I tried below code but it did not work.

```ini
[hotkey]
`;=<DirectoryHotlist>
```

Another question is that, I would like to combine some other custom global command, e.g. `<ToggleGVim>`, just similar like <ToggleTC>. I have quite limited knowledge of autohotkey. Previously I have a dedicated script to achieve that using the snippet blow. But if I directly paste it into "ViATc-0.5.5en.ahk" and reload, ViATc would just not run at all. Could you provide some guides on how to add a custom global command like `<ToggleGVim>` in ViATc? Thanks

```autohotkey
#v::
DetectHiddenWindows, on
IfWinNotExist ahk_class Vim
	Run, c:\Program Files\Vim\Vim82\gvim.exe,,max
Else
IfWinNotActive ahk_class Vim
	WinActivate
Else
	WinMinimize
Return
```

**Comment by magicstep** [comment]
I'm glad you find ViATc useful. The original author is linxinhong, I took over a few years ago.

I will add an option to map a semicolon, mapping it in the ini file doesn't work as it is a special character for comments in ini files. The backtick doesn't escape characters in ini files, it does in ahk files.
You can remap the following line in the ViATc  script
```
	Hotkey,`;,<FocusCmdLine>,On,UseErrorLevel
```

The `<ToggleGVim>` snippet is nice idea, I may add it. Personally I have pinned gVim to the taskbar at the top so `#1` toggles vim for me without any scripts, it's a Windows thing you can use digits 1 to 0. The `#v` is a new shortcut in Windows, it is for a multi-clipboard.
For all other snippets it is easier to have your own separate script. So in case of ViATc update you will still keep your snippets. Two examples of a snippet file:
```
#If WinActive("ahk_exe totalcmd64.exe")
   ; your snippets go here
#If
```
or 
```
#IfWinActive ahk_exe totalcmd64.exe
   ; your snippets go here
#IfWinActive
```

The ViATc script is a monster, and it's easy to get lost, I keep adding some snippets at the very bottom below the line: 
`;----------------- Aux ----------`

The `<SetTitleAsDateTime>`  snippet is quite easy, to make your own, just duplicate every occurrence of `SetTitleAsDateTime` changing it to custom name

**Comment by magicstep** [comment]
You can now remap special characters in viatc.ini
```
[SpecialHotkey]
; --- Special characters in ini files
;   The following four characters:  space ; = [  are not allowed as keys in ini files 
;   thus they cannot be directly remapped as hotkeys (nor be used as marks in ViATc).
;   Below is a workaround, uncomment any line and change value to your liking
;Char_space=<ListMapKey>
;Char_semicolon=<ListMapKey>
;Char_equals=<ListMapKey>
;Char_[=<ListMapKey>
```

**Comment by magicstep** [comment]
The newest version has the user.ahk file which is for your custom commands, mappings and any additions to the ViATc

**Comment by magicstep** [comment]
The newest version has the user.ahk file which is for your custom commands, mappings and any additions to the ViATc

**Comment by hongyuanjia** [comment]
That's great! Will try it out. Thanks for this great work
