### ISSUE TITLE
Suggestions for improving compatibility with other software (English translation by DeepL)

### ISSUE THREAD

**Issue by photkey** [magicstep/ViATc-English#8]
First of all I'm very sorry I can't communicate with you in English, the following English is from DeepL translation.
Thank you so much for maintaining this project, as the original author has stopped maintaining it and I've been looking forward to someone continuing it for a long time, and I'm very happy, shall we say excited, to see your project today, thank you again!
I've been using another efficiency tool written by AHK: RunAny (https://github.com/hui-Zz/RunAny), unfortunately it's not compatible with linsinhong's project, just tested your script with the same problem, when I press the shortcut start key - (the one above Tab), RunAny doesn't work properly, of course there are many other shortcuts for RunAny, most of them don't work properly, there are also some that do.
I think a solution to this problem might be to add a blacklisted key list to ViATc's config entry, where keys (including combo shortcuts) in this list perform their original actions when pressed, ignoring which mode of VIM ViATc is in at the time, and just performing them as they would without ViATc. I suspect this would be more compatible not only with RunAny, but with other software as well.
Thanks again for your continued maintenance of this project.
-------------------------------------------
非常感谢你对这个项目的维护，因为原作者已经停止维护了，我期待有人继续维护已经很久了，今天非常开心看到你的项目，应该说是激动，再次感谢你！
说一下我遇到的问题，我一直在使用另外一款由AHK编写的效率神器：RunAny（https://github.com/hui-Zz/RunAny），遗憾的是不能跟linxinhong的项目兼容，刚才测试了你的脚本也是同样的问题，当我按下快捷启动键 ·（Tab上面的那个键）时，RunAny无法正常运行，当然RunAny还有很多其它的快捷键，大多都不能正常运行，也有可以正常运行的。
我想解决这个问题的办法或许是在ViATc的配置项中增加一项黑名单键列表，在这个列表里面的键（包括组合快捷键），按下时执行他们本来的动作，忽略ViATc当时处于VIM的哪一种模式，只是按照没有ViATc时那样执行。我猜想这样不光是跟RunAny的兼容性更好，跟其它软件的兼容性也会更好的。
再次感谢您对这个项目的持续维护。

**Comment by magicstep** [comment]
Your translated message is easy to read, and RunAny looks interesting, I'm just reading about it.
My first advice for you is to remap all conflicting keys in the ini file as `<none>`   especially the backtick which is also called an accent key or the key between Esc and Tab.
You can also disable the ViATc in several ways: from the tray icon, or using shortcut alt+bactick, or by mapping those two commands:
`<ToggleViATc>    " Enable / Disable most of ViATc, global shortcuts will still work. For disabling all use <ViATcVimOff>"
<ViATcVimOff>    " Switch-off all ViATc functionality till Esc will switch on. This is more than <ToggleViATc>"`


Long term solution for me to do is as you said to create a blacklist key list, or in another words a pass-through key list or ignore  key list.

**Comment by llinfeng** [comment]
@photkey If you find the backtick button stepping in your way, you can comment out the following two lines in `viatc.ini`. These are all the backtick related shortcuts I found there.
1. [`` `=<CompareDirs>``](https://github.com/magicstep/ViATc-English/blob/a1cddcb1d1fde4da09396881de99b6a072a83e60/viatc.ini#L111) on line 111
2. [`` <Ctrl>`=<ListMapKeyMultiColumn>``](https://github.com/magicstep/ViATc-English/blob/a1cddcb1d1fde4da09396881de99b6a072a83e60/viatc.ini#L134) on line 134

中文：你可以去`viatc.ini`里面找找有 `` ` `` 的代码，我找到了上面这两个，整行去掉之后至少 ViATc 不会再占用这个键了。（也可以在最前面加个 `;` 把它隐藏起来。）

----

@magicstep, many thanks for maintaining ViATc! It was a huge relief to find it working with the 64-bit Total Commander program. A few hours ago, a brand-new Windows update screwed up my 32-bit TC installation where the program shall crash within seconds. Switching to 64-bit TC helped to stop the programming from crashing, but my old ViATc script stopped to work with the 64-bit TC. Thanks again for saving me hours from either bugging Christian (author for TC) about the corrupted `ntdll.dll` file in `c:\Windows\System32\` or spending a good Saturday afternoon reinstalling Windows :)
