### ISSUE TITLE
Old ViATc behaviors - may I override `e` for context menu and restore `o` and `O` mappings?

### ISSUE THREAD

**Issue by llinfeng** [magicstep/ViATc-English#9]
I am new to the modern ViATc and wonder if I may force it to act in a simpler manner? 

For `e`, my muscle memory tells me that it should summon the context menu. In `viatc.ini`, I made a new entry `e=<ContextMenu>` under `[ComboKey]`. The mapping is working as intended, but I am prompted with the following helper note. May I hide the following note?
![image](https://user-images.githubusercontent.com/5890407/120081037-6acffc00-c089-11eb-81c9-1452b13ae6dd.png)
Also, uncommenting [`;HotKey,e,<ContextMenu>,on,UseErrorLevel`](https://github.com/magicstep/ViATc-English/blob/a1cddcb1d1fde4da09396881de99b6a072a83e60/ViATc-0.5.5en.ahk#L2485) does not help.

Secondly, in an old ViATc, `o` will open the drive list on the left panel, and `O` will open the drive list on the right panel. With the current master branch, how may I overwrite the mapping for `o` and `O`? In `ViATc-0.5.5en.ahk`, I replaced the mapping for `o` and `+o` with the following. Still, `o` and `O` are behaving in its original manner as in the master branch.
```
	HotKey,o,<LeftOpenDrives>,on,UseErrorLevel
	HotKey,+o,<RightOpenDrives>,on,UseErrorLevel
```
Please advise if `o` and `O` are mapped somewhere else. I'd like to assign `o` for `cm_LeftOpenDrives` and `O` for `cm_RightOpenDrives` if possible. (Ref for `cm_LeftOpenDrives` and `cm_RightOpenDrives`: https://www.ghisler.ch/wiki/index.php/Totalcmd.inc)

**Comment by magicstep** [comment]
`e=<ContextMenu>`  should be under `[Hotkey]`   you said you've mapped it under `[ComboKey]`
Please also under `[ComboKey]` comment-out or delete all mappings for e_  like ec ey ep ed

**Comment by magicstep** [comment]
The command with label `<RightOpenDrives>` did not exist, instead it was without "s" at the end  `<RightOpenDrive>`
I updated the script with "s"  so it is consistent with other 

I was able to remap temporarily the way you want o for left and +o for right. It was just for test and it worked, but I left  the way it was.

**Comment by llinfeng** [comment]
@magicstep Thanks a lot for your quick response and the new commit. I forked this repo and applied a few edits to restore the functions according to my muscle memory :)
